name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-ui:
    name: UI Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.4.0
          run_install: true
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 22.19.0
      - name: Lint Check
        working-directory: ./ui
        run: pnpm run lint

  test-backend:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.22.4
          cache: true
      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsqlite3-dev libwebp-dev
      - name: Go Test
        run: go test -tags dev -v ./...
